default_stages: [commit]
repos:
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.12.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.0
  hooks:
    - id: require-ascii
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-executables-have-shebangs
