#!/bin/bash
set -euo pipefail
set -x
WORKDIR=$(pwd)

cleanup_vagrant_leftovers() {
  echo "Cleaning up Vagrant leftovers (if any)"
  set +e
  # TODO(cmaloney): Move to killing in virtualbox dirrectly? (rm -rf "~/VirtualBox VMs")
  vagrant destroy -f

  set +e
  for box in $( vboxmanage list vms | grep .dcos | cut -d '{' -f 2 | tr -d '}' ); do
    vboxmanage controlvm "$box" poweroff
    vboxmanage unregistervm "$box" --delete;
  done
  set -e

  vagrant global-status --prune
  set -e
}

echo "Fetching dcos-vagrant"

# Get the dcos-vagrant
# TODO(cmaloney): Have TeamCity do this for us.
# If it already exists, fetch, otherwise clone
if [ ! -d dcos-vagrant ]; then
  git clone https://github.com/dcos/dcos-vagrant
else
  git -C dcos-vagrant fetch origin -t +refs/heads/*:refs/remotes/origin/*
fi

# Pin to just the right dcos-vagrant commit
git -C dcos-vagrant checkout -qf 7b0b56bde93b8f2b65bb9ec50cd8a0ca932033b2

cp ../dcos_generate_config.sh dcos-vagrant/dcos_generate_config.sh

cd dcos-vagrant

# Make sure we're running inside the test directory which contains the Vagrantfile
if [ ! -f Vagrantfile ]
then
  echo "Expected a Vagrantfile inside the dcos-vagrant repo"
  exit 1
fi

# Flag used so TeamCity can tell if the build passed or failed. On failure,
# TeamCity will get logs from vagrant if possible then cleanup all artifacts.
rm -rf PASSED

export MASTER_IP=192.168.65.90
export DCOS_DNS_ADDRESS=http://$MASTER_IP
export MASTER_HOSTS=192.168.65.90,192.168.65.95,192.168.65.101

cp VagrantConfig.yaml.example VagrantConfig.yaml
export DCOS_INSTALL_METHOD="ssh_pull"
export DCOS_CONFIG_PATH="etc/3_master.yaml"
export DCOS_PRIVATE_REGISTRY="true"
cat <<EOF > "$DCOS_CONFIG_PATH"
---
cluster_name: test_cluster
bootstrap_url: http://boot.dcos
dns_search: mesos
exhibitor_storage_backend: zookeeper
exhibitor_zk_hosts: 192.168.65.50:2181
exhibitor_zk_path: /zk-shared
master_discovery: static
master_list:
  - 192.168.65.90
  - 192.168.65.95
  - 192.168.65.101
oauth_enabled: 'false'
EOF

cleanup_vagrant_leftovers

echo "Starting Vagrant VMs"

vagrant up m1 m2 m3 a1 a2 p1 boot

# TODO(cmaloney): Configure insecure registry inside the dcos-vagrant cluster

# Prep for the integration test after vagrant up so that it happens in parallel
# with DC/OS assembling itself to save some time.
# Build a docker container for running py.test inside of.
echo "Building py.test container"
docker build -t py.test - < ../docker/py.test/Dockerfile

# Build and push test server to local registry:
echo "Building&pushing test_server container"
docker build -t 127.0.0.1:5000/test_server -f ../docker/test_server/Dockerfile ../docker/test_server/

# Make an ssh tunnel to the vagrant machine then push the container over it to get around
# host insecure registry setting...
vagrant ssh boot -- -N -L 5000:192.168.65.50:5000 -f && docker push 127.0.0.1:5000/test_server

echo "Running integration test"
set +e # So we can potentially capture the logs

docker run -v $PWD/../integration_test.py:/integration_test.py \
    -e DCOS_DNS_ADDRESS=$DCOS_DNS_ADDRESS \
    -e MASTER_HOSTS=$MASTER_HOSTS \
    -e PUBLIC_MASTER_HOSTS=$MASTER_HOSTS \
    -e SLAVE_HOSTS="192.168.65.111,192.168.65.121" \
    -e PUBLIC_SLAVE_HOSTS="192.168.65.60" \
    -e REGISTRY_HOST="boot.dcos" \
    -e "TEAMCITY_VERSION=${TEAMCITY_VERSION:-}" \
    -e "DNS_SEARCH=true" \
    -e "DCOS_AUTH_ENABLED=false" \
    --net=host py.test py.test -vv -s -m "not minuteman and not ccm" ${CI_FLAGS:-} /integration_test.py
RET=$?

mkdir -p $WORKDIR/test/vagrant-logs
if [ $RET -ne 0 ]; then
  echo "TEST FAILED"
  echo "Attempting to gather logs"
  export LOG_REPLAY_LINES=${LOG_REPLAY_LINES:=20}
  for i in boot m1 m2 m3 a1 a2 p1; do
    if [ "$TEAMCITY_BUILD_ENV" == "true" ]; then
      echo "##teamcity[blockOpened name='$i']"
      vagrant ssh $i -c "'sudo journalctl -n $LOG_REPLAY_LINES'"
      echo "##teamcity[blockClosed name='$i']"
    else
      vagrant ssh $i -c "'sudo journalctl -n $LOG_REPLAY_LINES'"
    fi
  done
  exit 1
fi

echo "Cleaning up vagrant"
vagrant destroy -f
set -e

touch PASSED
