custom_dcos_download_path = "https://downloads.dcos.io/dcos/testing/pull/6956/dcos_generate_config.sh"
custom_dcos_download_path_win = "https://downloads.dcos.io/dcos/testing/pull/6956/windows/dcos_generate_config_win.sh"
variant="open"
windowsagent_num="1"
expiration="8h"
