"""Winpanda: Application-wide constant objects.
"""

# Default local FS layout for DC/OS installation
DCOS_INSTALL_ROOT_DPATH_DFT = 'c:\\dcos'

DCOS_STATE_ROOT_DNAME_DFT = 'state'
DCOS_STATE_ROOT_DPATH_DFT = (
    f'{DCOS_INSTALL_ROOT_DPATH_DFT}\\{DCOS_STATE_ROOT_DNAME_DFT}'
)

DCOS_PKG_ROOT_DNAME_DFT = 'pkg'
DCOS_PKG_ROOT_DPATH_DFT = (
    f'{DCOS_INSTALL_ROOT_DPATH_DFT}\\{DCOS_PKG_ROOT_DNAME_DFT}'
)

DCOS_CFG_ROOT_DNAME_DFT = 'conf'
DCOS_CFG_ROOT_DPATH_DFT = (
    f'{DCOS_INSTALL_ROOT_DPATH_DFT}\\{DCOS_CFG_ROOT_DNAME_DFT}'
)

DCOS_REPO_ROOT_DNAME_DFT = 'packages'
DCOS_REPO_ROOT_DPATH_DFT = (
    f'{DCOS_INSTALL_ROOT_DPATH_DFT}\\{DCOS_REPO_ROOT_DNAME_DFT}'
)
