#!/usr/bin/pwsh

mkdir -p $env:PKG_PATH/etc/

cat <<EOF > $env:PKG_PATH/etc/pkgpanda-api.conf.py
WORK_DIR = '/run/dcos/pkgpanda-api/'
EOF

systemd_service=$env:PKG_PATH/dcos.target.wants/dcos-pkgpanda-api.service
mkdir -p $(dirname $systemd_service)
envsubst '${env:PKG_PATH}' < /pkg/extra/dcos-pkgpanda-api.service > "$systemd_service"

$dst_file=$env:PKG_PATH/pkgpanda-api/bin/pkgpanda-api.ps1
mkdir -p $(dirname $dst_file)
cp /pkg/extra/pkgpanda-api.sh $dst_file
chmod +x $dst_file
