package:
  - path: /etc/cfn_signal_metadata
    content: |
      AWS_REGION={{ aws_region }}
      AWS_STACK_ID={{ aws_stack_id }}
      AWS_STACK_NAME={{ aws_stack_name }}
      AWS_IAM_MASTER_ROLE_NAME={{ master_role }}
      AWS_IAM_SLAVE_ROLE_NAME={{ agent_role }}
