CONFIG_PATH = 'genconf/config.yaml'
SSH_KEY_PATH = 'genconf/ssh_key'
IP_DETECT_PATH = 'genconf/ip-detect'
SERVE_DIR = 'genconf/serve'
STATE_DIR = 'genconf/state'
GENERATED_CONFIG_DIR = 'genconf/generated-config/'
GENCONF_DIR = 'genconf'
