package:
  - path: /etc/repository-url
    permissions: "0644"
    content: |
      {{ bootstrap_url }}
  - path: /etc/cluster-package-list
    permissions: "0644"
    content: |
      {{ cluster_package_list_id }}
