# Before editing this file, ensure that you have the correct file.  This file
# (`dcos-config-win.yaml`) describes the contents of the `dcos-config-win`
# package.  The configuation files for Windows nodes are described in the
# `dcos-config-windows.yaml` file, a copy of which is added to the package.
package:
  - path: /pkginfo.json
    permissions: "0644"
    content: |
      {}
  - path: /expanded.config.full.json
    permissions: "0600"
    content: |
{{ expanded_config_full }}
  - path: /dcos-config-windows.yaml
    permissions: "0644"
    content: |
{{ windows_config_yaml }}
