# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mocker/endpoints/grpc_endpoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mocker/endpoints/grpc_endpoint.proto',
  package='etcdserverpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$mocker/endpoints/grpc_endpoint.proto\x12\x0c\x65tcdserverpb\" \n\rStringMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\nIntMessage\x12\x11\n\tmessageID\x18\x01 \x01(\x05\"*\n\x14IntCollectionMessage\x12\x12\n\nmessageIDs\x18\x01 \x03(\x05\x32\x97\x02\n\x0bMockService\x12N\n\x10UnaryDoSomething\x12\x1b.etcdserverpb.StringMessage\x1a\x1b.etcdserverpb.StringMessage\"\x00\x12[\n\x17\x43lientStreamDoSomething\x12\x18.etcdserverpb.IntMessage\x1a\".etcdserverpb.IntCollectionMessage\"\x00(\x01\x12[\n\x17ServerSteramDoSomething\x12\".etcdserverpb.IntCollectionMessage\x1a\x18.etcdserverpb.IntMessage\"\x00\x30\x01\x62\x06proto3')
)




_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='etcdserverpb.StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='etcdserverpb.StringMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=86,
)


_INTMESSAGE = _descriptor.Descriptor(
  name='IntMessage',
  full_name='etcdserverpb.IntMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageID', full_name='etcdserverpb.IntMessage.messageID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=119,
)


_INTCOLLECTIONMESSAGE = _descriptor.Descriptor(
  name='IntCollectionMessage',
  full_name='etcdserverpb.IntCollectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageIDs', full_name='etcdserverpb.IntCollectionMessage.messageIDs', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
DESCRIPTOR.message_types_by_name['IntMessage'] = _INTMESSAGE
DESCRIPTOR.message_types_by_name['IntCollectionMessage'] = _INTCOLLECTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), {
  'DESCRIPTOR' : _STRINGMESSAGE,
  '__module__' : 'mocker.endpoints.grpc_endpoint_pb2'
  # @@protoc_insertion_point(class_scope:etcdserverpb.StringMessage)
  })
_sym_db.RegisterMessage(StringMessage)

IntMessage = _reflection.GeneratedProtocolMessageType('IntMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTMESSAGE,
  '__module__' : 'mocker.endpoints.grpc_endpoint_pb2'
  # @@protoc_insertion_point(class_scope:etcdserverpb.IntMessage)
  })
_sym_db.RegisterMessage(IntMessage)

IntCollectionMessage = _reflection.GeneratedProtocolMessageType('IntCollectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTCOLLECTIONMESSAGE,
  '__module__' : 'mocker.endpoints.grpc_endpoint_pb2'
  # @@protoc_insertion_point(class_scope:etcdserverpb.IntCollectionMessage)
  })
_sym_db.RegisterMessage(IntCollectionMessage)



_MOCKSERVICE = _descriptor.ServiceDescriptor(
  name='MockService',
  full_name='etcdserverpb.MockService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=166,
  serialized_end=445,
  methods=[
  _descriptor.MethodDescriptor(
    name='UnaryDoSomething',
    full_name='etcdserverpb.MockService.UnaryDoSomething',
    index=0,
    containing_service=None,
    input_type=_STRINGMESSAGE,
    output_type=_STRINGMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClientStreamDoSomething',
    full_name='etcdserverpb.MockService.ClientStreamDoSomething',
    index=1,
    containing_service=None,
    input_type=_INTMESSAGE,
    output_type=_INTCOLLECTIONMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ServerSteramDoSomething',
    full_name='etcdserverpb.MockService.ServerSteramDoSomething',
    index=2,
    containing_service=None,
    input_type=_INTCOLLECTIONMESSAGE,
    output_type=_INTMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOCKSERVICE)

DESCRIPTOR.services_by_name['MockService'] = _MOCKSERVICE

# @@protoc_insertion_point(module_scope)
